### ISSUE TITLE
Miss mkbootimg.mk?

### ISSUE THREAD

**Issue by YumeMichi** [MasterAwesome/android_device_oneplus_onyx#1]

**Comment by MasterAwesome** [comment]
Source built dt.img doesn't work yet. So back to using prebuilt.

**Comment by MasterAwesome** [comment]
Fixed in this commit https://github.com/MasterAwesome/android_device_oneplus_onyx/commit/45de90748b73f38d6a9ff56034006e5206709611. :+1:
