### ISSUE TITLE
build succeed from source but phone can't boot

### ISSUE THREAD

**Issue by YumeMichi** [MasterAwesome/android_device_oneplus_onyx#2]
Hey MasterAwesome:

I am trying to build CM12.1 from source following your guide. But my phone just can't boot after I flash the ROM. It got stuck in 1+ logo and restart to recovery automatically.

This is my build process and local_manifests:
https://github.com/YumeMichi/opx_cm_build_env/blob/master/opx_cm_env.sh
https://github.com/YumeMichi/opx_cm_build_env/blob/master/local_manifests.xml

Screenshot:
http://i.imgur.com/YOypZvS.png

My ROM:
[cm-12.1-20151224-UNOFFICIAL-onyx.zip](http://download.ikke.moe/cm-12.1-20151224-UNOFFICIAL-onyx.zip)

**Comment by Fabio-San** [comment]
Revert this https://github.com/MasterAwesome/android_device_oneplus_onyx/commit/5f4054969a73c3b8ecef466ffdf46617e6b54b08

**Comment by MasterAwesome** [comment]
That's needed for init.cne.sh which is also required by netmgr. Which is required for mobile data.

**Comment by Fabio-San** [comment]
If are you referring to my answer, network mobile works also without that preload ;)

**Comment by MasterAwesome** [comment]
Cne depends on it though. Just add it to the vendor tree and issue a pull request.

**Comment by YumeMichi** [comment]
Thank you two.
